---
# tasks file for prometheus-node-exporter

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.7.0.linux-amd64.tar.gz

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create node_exporter service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Start and enable node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes