---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Docker container
      docker_container:
        name: instance
        image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}"
        state: started
        command: "/sbin/init"
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
        privileged: true